version: "3.3"

services:
  personal-website:
    image: ghcr.io/azat-ismagilov/azat-ismagilov.github.io:master
    container_name: personal-website
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.personal_website.rule=Host(`aismagilov.ru`, `ismagilov.de`)"
      - "traefik.http.routers.personal_website.entrypoints=websecure"
      - "traefik.http.routers.personal_website.tls.certresolver=letsencrypt"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - web

networks:
  web:
    external: true
